[template]
src = "fluent.conf.tmpl"
dest = "/fluentd/etc/fluent.conf"
keys = [
    "/fluentd/out/kubeuser/buffer/overflow/action",
    "/fluentd/out/kubeuser/buffer/chunk/limit/size",
    "/fluentd/out/kubeuser/buffer/total/limit/size",
    "/fluentd/out/kubeuser/buffer/flush/interval",
    "/fluentd/out/kubeuser/buffer/retry/max/interval",
    "/fluentd/out/kubeuser/retry/forever",
    "/fluentd/out/kubeuser/retry/limit",
    "/fluentd/out/kubeuser/flush/thread/count",
    "/fluentd/out/kubesys/buffer/overflow/action",
    "/fluentd/out/kubesys/buffer/chunk/limit/size",
    "/fluentd/out/kubesys/buffer/total/limit/size",
    "/fluentd/out/kubesys/buffer/flush/interval",
    "/fluentd/out/kubesys/buffer/retry/max/interval",
    "/fluentd/out/kubesys/retry/forever",
    "/fluentd/out/kubesys/retry/limit",
    "/fluentd/out/kubesys/flush/thread/count",
]
